### ISSUE TITLE
Key fee

### ISSUE THREAD

**Issue by mankoff** [tchughesiv/voice#1]
Is the Google Cloud API key available for free? It seems that this is not a free service, but am curious if that is correct or not.

**Comment by tchughesiv** [comment]
when i was using it i believe i was paying for it, but it was very cheap imo for what i was using it for.

**Comment by mankoff** [comment]
Got it - yes that is what I found. First 60 minutes are free, then they charge a reasonable rate: $0.006 USD / 15 seconds. Thank you!
